### PR TITLE
feat(srelogin): make srelogin upstreamable

### PR DESCRIPTION
**Pull request by georgettica**

### CODE REVIEW

**Comment by iamkirkbater** [comment]
I have mixed feelings about this.  Part of me wants to do it this way because it's easier, but the other part of me wants to just do a copy/paste or some other manual operation (make target, perhaps) that essentially makes a copy into our repo so we can commit it.

Thoughts on why:
1. What if Matt leaves?
2. What if Matt deletes the file?

Part of me also wants to consider that scripts like this should either live in a shared repo (think ops-sop/scripts) or live here and have Matt pull from here for his repo.

**Comment by georgettica** [comment]
both are fine, I just didn't want to make copies of the original and cause drift. as he is updating the script still..

once he settles we can request he moves it to a repo that is used by all.

or even better, create a clean branch of ops-sop and start migrating "good" scripts?

**Comment by iamkirkbater** [comment]
Yeah, I definitely understand the drift part, and I was super happy when you found the env vars so we were just able to just copy the script wholesale instead of having to modify it for our specific use-case locally.  

I did also pull the latest copy and commit that with that PR.

**Comment by georgettica** [comment]
I saw that, but maybe create a repo for step scripts and sops and have this script there? Not sure

**Comment by georgettica** [comment]
I should close this.. right?

**Pull request closed without merging**
